export default {
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
  TOGGLE_LOG_IN: 'TOGGLE_LOG_IN',
  TOGGLE_BACKGROUND_COLOR: 'TOGGLE_BACKGROUND_COLOR',
  TOGGLE_FONT_SIZE: 'TOGGLE_FONT_SIZE',
};
